In [34]:
# Show all output's on Jupyter Notebook
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Sequence Example - Fibonacci

In [12]:
# n = position of the sequence. 
# 0,1,1,2,3,...

def fibonacci(n):
    if n==0:
        return(0)
    if n==1:
        return(1)
    else:
        return(fibonacci(n-1)+fibonacci(n-2))
    
print(fibonacci(3))

2


# General $a_n$ Sequence Expression

In [54]:
import numpy as np

# Equation a_n - 2.a_(n-1) - a_(n-2) = 0
coef=[1, -2, -1]
roots = np.roots(coef)
roots

# Initial solutions - same number of roots
sol = np.array([[0], [1]])
    
# Roots matrix (for multiplication with coefficient matrix)
for i in range(len(roots)):
    if i==0:
        a = [np.power(roots,i)]
        b = [np.power(roots,i+1)]
        b = np.concatenate((a, b), axis=0)
    if i==1:
        pass
    if i>1:
        a = [np.power(roots,i)]
        b = np.concatenate((b, a), axis=0)

# Coefficient matrix - a_n = (coef1).(root1)^n + (coef2).(root2)^n + ...
# b.x = sol --> x = b^-1.sol
coef_matrix = np.linalg.solve(b, sol)
coef_matrix

# General solution (a_n) = (roots)^n . (coef_matrix)
n = 4
a_n = np.power(roots, n) @ coef_matrix
a_n.real

array([ 2.41421356, -0.41421356])

array([[ 0.35355339],
       [-0.35355339]])

array([12.])